### ISSUE TITLE
Подключить Google Tag Manager на форму sales

### ISSUE THREAD

**Issue by Ekmoroz** [Ekmoroz/remote-demo#1]
- First
- Second

@coursar, 943baf4d4db892f3ff7ae3865aee09794d80fa25

https://github.com/Ekmoroz/remote-demo/blob/943baf4d4db892f3ff7ae3865aee09794d80fa25/index.html#L6

**Comment by Ekmoroz** [comment]
Ok

**Comment by coursar** [comment]
меня-то зачем тегать? ))
